project:
  paths:
    log_dir: log
    checkpoint_base_dir: checkpoints
    artifacts_dir: artifacts
    root: .
  data_sources:
    mini_imagenet_path: ~/.cache/kagglehub/datasets/arjunashok33/miniimagenet/versions/1
  allen_data:
    neuropixels_url: https://mouse-vision-neuraldata.s3.amazonaws.com/mouse_neuropixels_visual_data_with_reliabilities.pkl
    calcium_url: https://mouse-vision-neuraldata.s3.amazonaws.com/mouse_calcium_visual_data_with_reliabilities.pkl
experiment:
  data:
    data_path: ~/.cache/kagglehub/datasets/arjunashok33/miniimagenet/versions/1
    image_size: 224
    batch_size: 256
    num_workers: 15
    train_split: 0.7
    val_split: 0.15
    split_seed: 42
  train:
    num_epochs: 200
    dropout_rate: 0.3
    early_stopping_patience: 100
    self_supervised: true
    checkpoint_sub_dir: self-supervised_diet
    optimizer:
      name: SGD
      params:
        lr: 0.03
        momentum: 0.9
        weight_decay: 0.0001
    scheduler:
      name: MultiStepLR
      params:
        milestones:
        - 120
        - 160
        - 180
        gamma: 0.2
    loss:
      name: InstanceDiscriminationLoss
      params:
        mode: dynamic
        m: 16384
        gamma: 0.5
        tau: 0.1
        embedding_dim: 128
        model_output_dim: 4096
        warmup_epochs: 5
        z_const: 1260.17
    save_every_n: 10
  device:
    device: auto
    use_cuda: true
    seed: 42
  logging:
    level: INFO
  diet:
    grayscale: true
    blur: true
    noise: true
root: /home/spina/Desktop/units/DL/project
run_dir: /home/spina/Desktop/units/DL/project/mice-representation-clean/checkpoints/self-supervised_diet/20251009_034006_warmup+dynamic-correct-no-aug
